name: "${pom.artifactId}"
main: hmmhmmmm.worldprotect.WorldProtect
author: "HmmHmmmm"
version: "${pom.version}"
api: ["1.0.9"]
website: https://github.com/HmmHmmmm

permissions:
    worldprotect.command:
        default: false
        children:
            worldprotect.command.worldprotect:
                default: op